-- INSERINDO OS VALORES DA TABELA PIZZA
	INSERT INTO pizzas VALUES
(1,'Calabresa', 'Grande', 'Pizza de calabresa com cebola e queijo', 35.90, 'Calabresa, cebola, queijo',1,1,1),
(2, 'Marguerita', 'Média', 'Pizza tradicional italiana com molho de tomate, queijo e manjericão', 29.90, 'Molho de tomate, queijo mussarela, manjericão',2,2,2),
(3,'Frango com Catupiry', 'Grande', 'Pizza de frango desfiado com catupiry cremoso', 38.50, 'Frango desfiado, catupiry, tomate',3,3,3),
(4,'Quatro Queijos', 'Média', 'Pizza com uma seleção de quatro queijos: mussarela, provolone, parmesão e gorgonzola', 32.00, 'Queijo mussarela, queijo provolone, queijo parmesão, queijo gorgonzola',4,4,4),
(5,'Portuguesa', 'Grande', 'Pizza à moda portuguesa com presunto, ovo, cebola, azeitonas e queijo', 37.00, 'Presunto, ovo, cebola, azeitonas, queijo',5,5,5),
(6,'Pepperoni', 'Média', 'Pizza com generosas fatias de pepperoni e queijo derretido', 30.50, 'Pepperoni, queijo mussarela',6,6,6),
(7,'Vegetariana', 'Grande', 'Pizza vegetariana com uma variedade de legumes frescos e queijo', 34.90, 'Abobrinha, pimentão, cebola, cogumelos, queijo',7,7,7),
(8,'Calabresa com Catupiry', 'Média', 'Combinação deliciosa de calabresa picante e catupiry cremoso', 33.00, 'Calabresa, catupiry, cebola',8,8,8),
(9,'Marguerita Especial', 'Grande', 'Versão especial da tradicional Marguerita com tomatinhos cereja e azeite trufado', 39.90, 'Molho de tomate, queijo mussarela, manjericão, tomatinhos cereja, azeite trufado',9,9,9),
(10,'Frango com Requeijão', 'Média', 'Pizza de frango desfiado com requeijão cremoso', 35.50, 'Frango desfiado, requeijão, cebola, tomate',10,10,10),
(11,'Quatro Estações', 'Grande', 'Pizza com quatro sabores em cada fatia: calabresa, frango, milho e portuguesa', 41.00, 'Calabresa, frango, milho, presunto, ovo, cebola, azeitonas',11,11,11),
(12,'Pepperoni Duplo', 'Média', 'Pizza com dobro de pepperoni para os amantes dessa iguaria', 32.50, 'Pepperoni, queijo mussarela',12,12,12),
(13,'Marguerita Vegana', 'Grande', 'Pizza Marguerita sem ingredientes de origem animal', 36.90, 'Molho de tomate, queijo vegano, manjericão',13,13,13),
(14,'Frango com Cheddar', 'Média', 'Pizza de frango desfiado com cheddar cremoso', 34.00, 'Frango desfiado, cheddar, cebola, pimentão',14,14,14),
(15,'Especial da Casa', 'Grande', 'Pizza com a seleção exclusiva de ingredientes da casa', 42.00, 'Ingredientes secretos da casa',15,15,15),
(16,'Napolitana', 'Média', 'Pizza napolitana com anchovas, azeitonas pretas, alcaparras e molho de tomate', 31.00, 'Anchovas, azeitonas pretas, alcaparras, molho de tomate, queijo',16,16,16),
(17,'Marguerita Light', 'Grande', 'Pizza Marguerita com ingredientes leves e menos calóricos', 38.90, 'Molho de tomate light, queijo light, manjericão fresco',17,17,17),
(18,'Frango à Moda da Casa', 'Média', 'Pizza de frango desfiado com ingredientes especiais da casa', 36.50, 'Frango desfiado, ingredientes secretos da casa',18,18,18),
(19,'Calabresa Especial', 'Grande', 'Pizza de calabresa especial com tempero exclusivo', 40.00, 'Calabresa especial, cebola, queijo',19,19,19),
(20,'Pepperoni Picante', 'Média', 'Pizza com pepperoni levemente picante e queijo derretido', 33.50, 'Pepperoni picante, queijo mussarela',20,20,20),
(21,'Vegetariana Light', 'Grande', 'Pizza vegetariana com ingredientes light e saudáveis', 37.90, 'Abobrinha, pimentão, cebola, cogumelos, queijo light',21,21,21),
(22,'Calabresa com Cheddar', 'Média', 'Pizza de calabresa picante com cheddar cremoso', 35.00, 'Calabresa picante, cheddar, cebola, pimentão',22,22,22),
(23,'Quatro Queijos Premium', 'Grande', 'Pizza com uma seleção premium de quatro queijos: brie, gruyère, parmesão e gorgonzola', 45.00, 'Queijo brie, queijo gruyère, queijo parmesão, queijo gorgonzola',23,23,23),
(24,'Pepperoni Especial', 'Média', 'Pizza com pepperoni especial e ingredientes exclusivos', 34.50, 'Pepperoni especial, queijo mussarela, tomate, cebola',24,24,24),
(25,'Vegetariana Premium', 'Grande', 'Pizza vegetariana premium com ingredientes exclusivos e selecionados', 39.90, 'Abobrinha, pimentão, cogumelos trufados, queijo premium',25,25,25),
(26,'Calabresa com Bacon', 'Média', 'Pizza de calabresa picante com bacon crocante', 36.00, 'Calabresa picante, bacon, queijo mussarela',26,26,26),
(27,'Três Queijos', 'Grande', 'Pizza com uma seleção de três queijos: mussarela, provolone e parmesão', 38.00, 'Queijo mussarela, queijo provolone, queijo parmesão',27,27,27),
(28,'Pepperoni Clássico', 'Média', 'Pizza com pepperoni clássico e queijo derretido', 32.00, 'Pepperoni, queijo mussarela',28,28,28),
(29,'Vegetariana Especial', 'Grande', 'Pizza vegetariana especial com ingredientes exclusivos', 42.90, 'Abobrinha, pimentão, cogumelos trufados, queijo especial',29,29,29),
(30,'Frango com Cream Cheese', 'Média', 'Pizza de frango desfiado com cream cheese cremoso', 36.50, 'Frango desfiado, cream cheese, cebola, tomate',30,30,30);