-- INSERINDO VALORES DA TABELA EMBALAGEM
INSERT INTO Embalagem (MATERIAL, TAMANHO, PRECO)  VALUES
('Papelão', 'Pequena', 1.50),
('Plástico', 'Média', 2.00),
('Papelão', 'Grande', 2.50),
('Papel', 'Pequena', 1.00),
('Plástico', 'Grande', 3.00),
('Papelão', 'Média', 2.00),
('Papel', 'Grande', 2.00),
('Plástico', 'Pequena', 1.50),
('Papel', 'Média', 1.50),
('Caixa de Isopor', 'Grande', 4.00),
('Papelão', 'Pequena', 1.50),
('Papelão', 'Média', 2.00),
('Plástico', 'Grande', 3.00),
('Caixa de Isopor', 'Pequena', 2.00),
('Caixa de Isopor', 'Média', 3.00),
('Papel', 'Pequena', 1.00),
('Papel', 'Média', 1.50),
('Plástico', 'Grande', 3.00),
('Caixa de Isopor', 'Pequena', 2.00),
('Caixa de Isopor', 'Média', 3.00),
('Plástico', 'Pequena', 1.50),
('Papel', 'Média', 1.50),
('Caixa de Isopor', 'Grande', 4.00),
('Papelão', 'Pequena', 1.50),
('Plástico', 'Média', 2.00),
('Caixa de Papelão', 'Grande', 3.50),
('Caixa de Papelão', 'Média', 2.50),
('Caixa de Papel', 'Grande', 2.00),
('Caixa de Papel', 'Média', 1.50),
('Caixa de Plástico', 'Média', 2.00);